spring:
  application:
    name: libEasy
  datasource:
    url: jdbc:postgresql://localhost:5432/libeasy
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 30
  elasticsearch:
    uris: http://localhost:9200
app:
  jwt:
    secret: "Mw4mW/A6YqPmeLQolBC6kX1DKB0Y+iOm3WmDWWqBMjc="
    access-ttl-ms: 900000
    refresh-ttl-ms: 1209600000
    issuer: "libEasy"
    audience: "libEasy-api"
